-- Optional staging seed data for Blue Moon.
-- Replace organizer_email values before relying on production roster reminders.

insert into public.events (
  id,
  source,
  title,
  category,
  status,
  location_name,
  city,
  postal_code,
  start_time,
  end_time,
  time_zone,
  organizer_name,
  organizer_email,
  organizer_role,
  max_participants,
  participant_count_seed,
  summary,
  description,
  bring,
  impact_metric,
  proof_summary,
  image_url,
  image_alt,
  published_at,
  completed_at
) values
  (
    'santa-monica-beach-cleanup',
    'seed',
    'Santa Monica Beach Cleanup',
    'Beach cleanup',
    'published',
    'Tower 24, Santa Monica Beach',
    'Santa Monica',
    '90401',
    '2026-05-16T09:00:00-07:00',
    '2026-05-16T11:00:00-07:00',
    'America/Los_Angeles',
    'Maya Chen',
    'maya.chen@example.com',
    'Local organizer',
    30,
    12,
    'A relaxed Saturday cleanup near Tower 24. Bags and gloves are provided; bring water and sun protection.',
    'Meet at the bike path entrance by Tower 24. We will split into small groups, clean for about 90 minutes, and take one quick group photo before wrapping. First-timers are welcome.',
    'Water, sunscreen, closed-toe shoes, and a hat.',
    null,
    null,
    'https://images.unsplash.com/photo-1751646312140-42e2dd2b2b23?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800',
    'Volunteers sorting trash collected during a beach cleanup.',
    now(),
    null
  ),
  (
    'echo-park-garden-morning',
    'seed',
    'Echo Park Garden Morning',
    'Community garden',
    'published',
    'Lemoyne Street Community Garden',
    'Los Angeles',
    '90026',
    '2026-05-24T10:00:00-07:00',
    '2026-05-24T12:00:00-07:00',
    'America/Los_Angeles',
    'Jules Rivera',
    'jules.rivera@example.com',
    'Garden volunteer',
    18,
    7,
    'Help weed, mulch, and prep two shared beds for summer vegetables.',
    'This is a low-key garden morning for neighbors who want to help keep the shared beds healthy. Tools are available on site, and no gardening experience is needed.',
    'Reusable water bottle, clothes that can get dirty, and garden gloves if you have them.',
    null,
    null,
    'https://images.unsplash.com/photo-1665395131429-e1ee267da39a?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800',
    'A volunteer gardening in a sunny green space.',
    now(),
    null
  ),
  (
    'venice-food-pantry-pack',
    'seed',
    'Venice Food Pantry Pack',
    'Food help',
    'published',
    'Oakwood Recreation Center',
    'Los Angeles',
    '90291',
    '2026-05-21T18:00:00-07:00',
    '2026-05-21T19:30:00-07:00',
    'America/Los_Angeles',
    'Nia Brooks',
    'nia.brooks@example.com',
    'Pantry coordinator',
    24,
    16,
    'Pack pantry bags for Friday distribution. Come for the whole shift or the first hour.',
    'We will sort produce, pack pantry bags, and set up the room for the next morning''s distribution. The work is indoors and friendly to new volunteers.',
    'Comfortable shoes and a light jacket.',
    null,
    null,
    'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800',
    'Volunteers carrying boxes for food distribution.',
    now(),
    null
  ),
  (
    'palisades-park-proof',
    'seed',
    'Palisades Park Cleanup',
    'Park cleanup',
    'completed',
    'Palisades Park, Ocean Avenue',
    'Santa Monica',
    '90402',
    '2026-04-25T08:30:00-07:00',
    '2026-04-25T10:30:00-07:00',
    'America/Los_Angeles',
    'Sam Patel',
    'sam.patel@example.com',
    'Neighborhood host',
    20,
    14,
    'A completed cleanup with photos and a simple impact note.',
    'Neighbors met near Idaho Avenue, cleaned the lawn and path edges, and finished with a quick coffee stop.',
    'Completed event.',
    '14 people joined; 9 bags collected; 2 hours outside',
    'The group filled nine bags, cleared the overlook path, and left the park visibly cleaner before the morning crowds arrived.',
    'https://images.unsplash.com/photo-1758599668429-121d54188b9c?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800',
    'Volunteers cleaning a park with blue trash bags.',
    now(),
    '2026-04-25T10:30:00-07:00'
  )
on conflict (id) do update set
  source = excluded.source,
  title = excluded.title,
  category = excluded.category,
  status = excluded.status,
  location_name = excluded.location_name,
  city = excluded.city,
  postal_code = excluded.postal_code,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  time_zone = excluded.time_zone,
  organizer_name = excluded.organizer_name,
  organizer_email = excluded.organizer_email,
  organizer_role = excluded.organizer_role,
  max_participants = excluded.max_participants,
  participant_count_seed = excluded.participant_count_seed,
  summary = excluded.summary,
  description = excluded.description,
  bring = excluded.bring,
  impact_metric = excluded.impact_metric,
  proof_summary = excluded.proof_summary,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  published_at = coalesce(public.events.published_at, excluded.published_at),
  completed_at = excluded.completed_at,
  updated_at = now();

insert into public.event_proofs (
  event_id,
  status,
  summary,
  impact_metric,
  image_url,
  image_alt
) values (
  'palisades-park-proof',
  'published',
  'The group filled nine bags, cleared the overlook path, and left the park visibly cleaner before the morning crowds arrived.',
  '14 people joined; 9 bags collected; 2 hours outside',
  'https://images.unsplash.com/photo-1758599668429-121d54188b9c?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800',
  'Volunteers cleaning a park with blue trash bags.'
)
on conflict (event_id) do update set
  status = excluded.status,
  summary = excluded.summary,
  impact_metric = excluded.impact_metric,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  updated_at = now();
