window.BLUE_MOON_EVENTS = [
  {
    id: "santa-monica-beach-cleanup",
    title: "Santa Monica Beach Cleanup",
    category: "Beach cleanup",
    status: "published",
    locationName: "Tower 24, Santa Monica Beach",
    dateLabel: "Saturday, May 16, 2026",
    timeLabel: "9:00 AM - 11:00 AM",
    dateTime: "2026-05-16T09:00:00-07:00",
    organizer: "Maya Chen",
    organizerRole: "Local organizer",
    participantCount: 12,
    maxParticipants: 30,
    imageUrl: "https://images.unsplash.com/photo-1751646312140-42e2dd2b2b23?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800",
    imageAlt: "Volunteers sorting trash collected during a beach cleanup.",
    summary: "A relaxed Saturday cleanup near Tower 24. Bags and gloves are provided; bring water and sun protection.",
    description: "Meet at the bike path entrance by Tower 24. We will split into small groups, clean for about 90 minutes, and take one quick group photo before wrapping. First-timers are welcome.",
    bring: "Water, sunscreen, closed-toe shoes, and a hat.",
    impactMetric: null,
    proofSummary: null
  },
  {
    id: "echo-park-garden-morning",
    title: "Echo Park Garden Morning",
    category: "Community garden",
    status: "published",
    locationName: "Lemoyne Street Community Garden",
    dateLabel: "Sunday, May 24, 2026",
    timeLabel: "10:00 AM - 12:00 PM",
    dateTime: "2026-05-24T10:00:00-07:00",
    organizer: "Jules Rivera",
    organizerRole: "Garden volunteer",
    participantCount: 7,
    maxParticipants: 18,
    imageUrl: "https://images.unsplash.com/photo-1665395131429-e1ee267da39a?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800",
    imageAlt: "A volunteer gardening in a sunny green space.",
    summary: "Help weed, mulch, and prep two shared beds for summer vegetables.",
    description: "This is a low-key garden morning for neighbors who want to help keep the shared beds healthy. Tools are available on site, and no gardening experience is needed.",
    bring: "Reusable water bottle, clothes that can get dirty, and garden gloves if you have them.",
    impactMetric: null,
    proofSummary: null
  },
  {
    id: "venice-food-pantry-pack",
    title: "Venice Food Pantry Pack",
    category: "Food help",
    status: "published",
    locationName: "Oakwood Recreation Center",
    dateLabel: "Thursday, May 21, 2026",
    timeLabel: "6:00 PM - 7:30 PM",
    dateTime: "2026-05-21T18:00:00-07:00",
    organizer: "Nia Brooks",
    organizerRole: "Pantry coordinator",
    participantCount: 16,
    maxParticipants: 24,
    imageUrl: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800",
    imageAlt: "Volunteers carrying boxes for food distribution.",
    summary: "Pack pantry bags for Friday distribution. Come for the whole shift or the first hour.",
    description: "We will sort produce, pack pantry bags, and set up the room for the next morning's distribution. The work is indoors and friendly to new volunteers.",
    bring: "Comfortable shoes and a light jacket.",
    impactMetric: null,
    proofSummary: null
  },
  {
    id: "palisades-park-proof",
    title: "Palisades Park Cleanup",
    category: "Park cleanup",
    status: "completed",
    locationName: "Palisades Park, Ocean Avenue",
    dateLabel: "Saturday, April 25, 2026",
    timeLabel: "8:30 AM - 10:30 AM",
    dateTime: "2026-04-25T08:30:00-07:00",
    organizer: "Sam Patel",
    organizerRole: "Neighborhood host",
    participantCount: 14,
    maxParticipants: 20,
    imageUrl: "https://images.unsplash.com/photo-1758599668429-121d54188b9c?auto=format&fit=crop&fm=jpg&ixlib=rb-4.1.0&q=70&w=1800",
    imageAlt: "Volunteers cleaning a park with blue trash bags.",
    summary: "A completed cleanup with photos and a simple impact note.",
    description: "Neighbors met near Idaho Avenue, cleaned the lawn and path edges, and finished with a quick coffee stop.",
    bring: "Completed event.",
    impactMetric: "14 people joined · 9 bags collected · 2 hours outside",
    proofSummary: "The group filled nine bags, cleared the overlook path, and left the park visibly cleaner before the morning crowds arrived."
  }
];
